import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { 
  FiArrowLeft, FiCopy, FiCheck, FiShare2, FiDownload, 
  FiTrendingUp, FiAlertTriangle, FiBookOpen, FiClock, FiPlusCircle,
  FiSmile, FiHelpCircle, FiHexagon, FiShield, FiZap, FiGrid
} from 'react-icons/fi';
import CircularScore from '../components/CircularScore';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas-pro';

export default function Dashboard({ data, onBack }) {
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);
  const [exporting, setExporting] = useState(false);

  const rec = data.recommendation || "Watchlist";
  const scores = data.scores || {
    marketPosition: 12,
    growthPotential: 12,
    financialHealth: 12,
    newsSentiment: 9,
    competitiveAdvantage: 9,
    riskExposure: 6,
    total: 60
  };

  const handleCopy = () => {
    const swotText = `
### SWOT Analysis
- **Strengths**:
${(data.swot?.strengths || []).map(s => `  - ${s}`).join('\n')}
- **Weaknesses**:
${(data.swot?.weaknesses || []).map(w => `  - ${w}`).join('\n')}
- **Opportunities**:
${(data.swot?.opportunities || []).map(o => `  - ${o}`).join('\n')}
- **Threats**:
${(data.swot?.threats || []).map(t => `  - ${t}`).join('\n')}
`;

    const reportMarkdown = `# Investment Analysis Report: ${data.company}
**Recommendation Verdict**: ${rec} (Total Score: ${scores.total}/100)

## Executive Summary
${data.overview}

## Category Scores
- Market Position: ${scores.marketPosition}/20
- Growth Potential: ${scores.growthPotential}/20
- Financial Health: ${scores.financialHealth}/20
- News Sentiment: ${scores.newsSentiment}/15
- Competitive Advantage: ${scores.competitiveAdvantage}/15
- Risk Exposure: ${scores.riskExposure}/10

${swotText}

## News & Source Citations
${(data.news || []).map(n => `- **${n.title}** (${n.source} - ${n.date})\n  ${n.summary}`).join('\n')}

## Why this Decision?
- **Score Rationale**: ${data.whyDecision?.scoreRationale || ""}
- **Recommendation Rationale**: ${data.whyDecision?.recommendationRationale || ""}
- **Risks Rationale**: ${data.whyDecision?.risksRationale || ""}

## Warren Buffett Value Perspective
${data.buffettPerspective || ""}

## Final Detailed Rationale
${data.reasoning}

---
*Generated by Valuation.AI - Smart Agentic Research Platforms on ${new Date().toLocaleDateString()}*`;

    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShare = () => {
    const shareUrl = `${window.location.origin}?company=${encodeURIComponent(data.company)}`;
    navigator.clipboard.writeText(shareUrl);
    setShared(true);
    setTimeout(() => setShared(false), 2000);
  };

  const handleExportPDF = () => {
    setExporting(true);
    const element = document.getElementById('report-dashboard-capture');
    
    html2canvas(element, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#030712',
      logging: false,
    })
    .then((canvas) => {
      const imgData = canvas.toDataURL('image/jpeg', 0.95);
      
      const pdf = new jsPDF('p', 'mm', 'a4');
      const imgWidth = 210; // A4 width in mm
      const pageHeight = 297; // A4 height in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 0;

      // Add first page
      pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      // Add subsequent pages if canvas height exceeds A4 height
      while (heightLeft > 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }
      
      pdf.save(`${data.company}_Valuation_Report.pdf`);
      setExporting(false);
    })
    .catch((err) => {
      console.error("PDF generation failed:", err);
      setExporting(false);
    });
  };

  const getRecStyles = (recText) => {
    const r = recText.toLowerCase();
    if (r.includes("strong")) {
      return { 
        text: "text-emerald-400", 
        border: "border-emerald-500/30", 
        bg: "bg-emerald-500/10 shadow-[0_0_20px_rgba(16,185,129,0.15)]",
        glow: "bg-emerald-500/10"
      };
    }
    if (r.includes("watchlist")) {
      return { 
        text: "text-amber-400", 
        border: "border-amber-500/30", 
        bg: "bg-amber-500/10 shadow-[0_0_20px_rgba(245,158,11,0.15)]",
        glow: "bg-amber-500/10"
      };
    }
    if (r.includes("pass")) {
      return { 
        text: "text-rose-400", 
        border: "border-rose-500/30", 
        bg: "bg-rose-500/10 shadow-[0_0_20px_rgba(239,68,68,0.15)]",
        glow: "bg-rose-500/10"
      };
    }
    // Default: Invest
    return { 
      text: "text-green-400", 
      border: "border-green-500/30", 
      bg: "bg-green-500/10 shadow-[0_0_20px_rgba(34,197,94,0.15)]",
      glow: "bg-green-500/10"
    };
  };

  const theme = getRecStyles(rec);

  const containerVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.05
      }
    }
  };

  const cardVariants = {
    hidden: { opacity: 0, y: 12 },
    show: { opacity: 1, y: 0, transition: { type: "spring", stiffness: 100 } }
  };

  return (
    <div className="min-h-screen py-6 px-4 sm:px-6 lg:px-8 w-full max-w-7xl mx-auto">
      {/* Action header bar */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6 relative z-20">
        <button
          onClick={onBack}
          className="flex items-center gap-2 text-sm text-gray-400 hover:text-white transition-colors duration-200 cursor-pointer self-start"
        >
          <FiArrowLeft /> Return to Search
        </button>

        <div className="flex items-center gap-3 self-end sm:self-auto">
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2 rounded-lg glass-input text-xs font-semibold text-gray-300 hover:text-white transition-all cursor-pointer hover:bg-white/5 active:scale-95"
          >
            {copied ? <><FiCheck className="text-emerald-400" /> Copied!</> : <><FiCopy /> Copy Markdown</>}
          </button>

          <button
            onClick={handleShare}
            className="flex items-center gap-2 px-4 py-2 rounded-lg glass-input text-xs font-semibold text-gray-300 hover:text-white transition-all cursor-pointer hover:bg-white/5 active:scale-95"
          >
            {shared ? <><FiCheck className="text-emerald-400" /> Link Copied!</> : <><FiShare2 /> Share Report</>}
          </button>

          <button
            onClick={handleExportPDF}
            disabled={exporting}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-violet-600 hover:bg-violet-500 disabled:bg-violet-800 disabled:cursor-not-allowed text-xs font-semibold text-white transition-all cursor-pointer shadow-lg shadow-violet-500/20 active:scale-95"
          >
            <FiDownload />
            {exporting ? "Compiling PDF..." : "Export PDF"}
          </button>
        </div>
      </div>

      {/* Capture Container */}
      <div id="report-dashboard-capture" className="space-y-6 bg-[#030712] p-1 rounded-2xl">
        <div className="flex flex-col md:flex-row items-center justify-between gap-6 pb-6 border-b border-white/5">
          <div>
            <span className="text-xs font-bold tracking-widest text-violet-400 uppercase">AI Institutional Research Brief</span>
            <h1 className="text-4xl md:text-5xl font-extrabold text-white mt-1">{data.company}</h1>
            <p className="text-xs text-gray-500 mt-1">Generated: {new Date().toLocaleDateString()} | Multi-Agent Execution Verified</p>
          </div>
          <div className="flex items-center gap-4">
            <div className={`px-5 py-2 rounded-full border text-xs font-extrabold tracking-wider ${theme.text} ${theme.border} ${theme.bg}`}>
              {rec.toUpperCase()}
            </div>
          </div>
        </div>

        <motion.div
          variants={containerVariants}
          initial="hidden"
          animate="show"
          className="grid grid-cols-1 lg:grid-cols-12 gap-6"
        >
          {/* LEFT COLUMN: Overview, Circular Gauge, Category Scores (5 Cols) */}
          <div className="lg:col-span-5 space-y-6">
            {/* Score Ring Card */}
            <motion.div variants={cardVariants} className="glass-card rounded-2xl p-6 relative overflow-hidden border border-white/5">
              <div className={`absolute -top-12 -left-12 w-32 h-32 rounded-full blur-3xl pointer-events-none ${theme.glow}`} />
              <h3 className="text-sm font-semibold tracking-wider text-gray-400 uppercase mb-2 text-center">Valuation Score</h3>
              <CircularScore score={scores.total} decision={rec} />
            </motion.div>

            {/* Category Scores Breakdown */}
            <motion.div variants={cardVariants} className="glass-card rounded-2xl p-6 border border-white/5">
              <h3 className="text-sm font-semibold tracking-wider text-gray-400 uppercase mb-4 flex items-center gap-2">
                <FiHexagon className="text-violet-400" />
                <span>Scoring Category Breakdown</span>
              </h3>
              
              <div className="space-y-4">
                {[
                  { label: "Market Position", value: scores.marketPosition, max: 20, color: "bg-blue-500" },
                  { label: "Growth Potential", value: scores.growthPotential, max: 20, color: "bg-emerald-500" },
                  { label: "Financial Health", value: scores.financialHealth, max: 20, color: "bg-violet-500" },
                  { label: "Recent News Sentiment", value: scores.newsSentiment, max: 15, color: "bg-cyan-500" },
                  { label: "Competitive Advantage", value: scores.competitiveAdvantage, max: 15, color: "bg-fuchsia-500" },
                  { label: "Risk Exposure (Low = High Score)", value: scores.riskExposure, max: 10, color: "bg-rose-500" }
                ].map((item, idx) => {
                  const percent = (item.value / item.max) * 100;
                  return (
                    <div key={idx} className="space-y-1">
                      <div className="flex justify-between text-xs">
                        <span className="text-gray-400 font-light">{item.label}</span>
                        <span className="text-gray-200 font-semibold">{item.value} / {item.max}</span>
                      </div>
                      <div className="w-full h-1.5 bg-gray-800 rounded-full overflow-hidden">
                        <motion.div 
                          initial={{ width: 0 }}
                          animate={{ width: `${percent}%` }}
                          transition={{ duration: 1.2, ease: "easeOut" }}
                          className={`h-full ${item.color} rounded-full`}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
            </motion.div>

            {/* Executive Overview */}
            <motion.div variants={cardVariants} className="glass-card rounded-2xl p-6 border border-white/5">
              <h3 className="text-sm font-semibold tracking-wider text-gray-400 uppercase mb-3 flex items-center gap-2">
                <FiBookOpen className="text-violet-400" />
                <span>Executive Dossier</span>
              </h3>
              <p className="text-sm text-gray-300 leading-relaxed font-light">{data.overview}</p>
            </motion.div>
          </div>

          {/* RIGHT COLUMN: SWOT Matrix, News Timeline, Why Decision, Buffett Perspective (7 Cols) */}
          <div className="lg:col-span-7 space-y-6">
            
            {/* SWOT Grid */}
            <motion.div variants={cardVariants} className="glass-card rounded-2xl p-6 border border-white/5">
              <h3 className="text-sm font-semibold tracking-wider text-gray-400 uppercase mb-5 flex items-center gap-2">
                <FiGrid className="text-violet-400" />
                <span>SWOT Analysis</span>
              </h3>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Strengths */}
                <div className="glass-card bg-emerald-950/15 border-emerald-500/10 rounded-xl p-4">
                  <h4 className="text-xs font-bold text-emerald-400 uppercase mb-2 flex items-center gap-1.5">
                    <FiZap className="shrink-0" /> Strengths
                  </h4>
                  <ul className="space-y-2">
                    {(data.swot?.strengths || []).map((s, idx) => (
                      <li key={idx} className="text-xs text-gray-300 leading-relaxed font-light list-disc ml-3">{s}</li>
                    ))}
                  </ul>
                </div>

                {/* Weaknesses */}
                <div className="glass-card bg-amber-950/15 border-amber-500/10 rounded-xl p-4">
                  <h4 className="text-xs font-bold text-amber-400 uppercase mb-2 flex items-center gap-1.5">
                    <FiAlertTriangle className="shrink-0" /> Weaknesses
                  </h4>
                  <ul className="space-y-2">
                    {(data.swot?.weaknesses || []).map((w, idx) => (
                      <li key={idx} className="text-xs text-gray-300 leading-relaxed font-light list-disc ml-3">{w}</li>
                    ))}
                  </ul>
                </div>

                {/* Opportunities */}
                <div className="glass-card bg-blue-950/15 border-blue-500/10 rounded-xl p-4">
                  <h4 className="text-xs font-bold text-blue-400 uppercase mb-2 flex items-center gap-1.5">
                    <FiTrendingUp className="shrink-0" /> Opportunities
                  </h4>
                  <ul className="space-y-2">
                    {(data.swot?.opportunities || []).map((o, idx) => (
                      <li key={idx} className="text-xs text-gray-300 leading-relaxed font-light list-disc ml-3">{o}</li>
                    ))}
                  </ul>
                </div>

                {/* Threats */}
                <div className="glass-card bg-rose-950/15 border-rose-500/10 rounded-xl p-4">
                  <h4 className="text-xs font-bold text-rose-400 uppercase mb-2 flex items-center gap-1.5">
                    <FiShield className="shrink-0" /> Threats
                  </h4>
                  <ul className="space-y-2">
                    {(data.swot?.threats || []).map((t, idx) => (
                      <li key={idx} className="text-xs text-gray-300 leading-relaxed font-light list-disc ml-3">{t}</li>
                    ))}
                  </ul>
                </div>
              </div>
            </motion.div>

            {/* News Citations */}
            <motion.div variants={cardVariants} className="glass-card rounded-2xl p-6 border border-white/5 relative overflow-hidden">
              <h3 className="text-sm font-semibold tracking-wider text-gray-400 uppercase mb-4 flex items-center gap-2">
                <FiClock className="text-violet-400" />
                <span>Verified News & Citations</span>
              </h3>
              
              <div className="space-y-4">
                {(data.news || []).map((item, idx) => (
                  <div key={idx} className="p-4 bg-black/35 rounded-xl border border-white/5 space-y-2">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <h4 className="text-sm font-semibold text-white leading-tight">{item.title}</h4>
                      <div className="flex items-center gap-2 shrink-0">
                        <span className="text-[10px] bg-violet-600/15 text-violet-400 border border-violet-500/20 px-2 py-0.5 rounded-md font-mono">{item.source}</span>
                        <span className="text-[10px] text-gray-500">{item.date}</span>
                      </div>
                    </div>
                    <p className="text-xs text-gray-400 leading-relaxed font-light">{item.summary}</p>
                  </div>
                ))}
              </div>
            </motion.div>

            {/* Why This Decision Explanation */}
            <motion.div variants={cardVariants} className="glass-card rounded-2xl p-6 border border-white/5">
              <h3 className="text-sm font-semibold tracking-wider text-gray-400 uppercase mb-4 flex items-center gap-2">
                <FiHelpCircle className="text-violet-400" />
                <span>Why This Decision? (Explainability)</span>
              </h3>
              
              <div className="space-y-4 text-xs font-light">
                <div className="space-y-1">
                  <h5 className="font-semibold text-gray-300">Scoring Rationale</h5>
                  <p className="text-gray-400 leading-relaxed">{data.whyDecision?.scoreRationale}</p>
                </div>
                <div className="space-y-1 border-t border-white/5 pt-3">
                  <h5 className="font-semibold text-gray-300">Recommendation Verdict</h5>
                  <p className="text-gray-400 leading-relaxed">{data.whyDecision?.recommendationRationale}</p>
                </div>
                <div className="space-y-1 border-t border-white/5 pt-3">
                  <h5 className="font-semibold text-gray-300">Risk Assessment Weighting</h5>
                  <p className="text-gray-400 leading-relaxed">{data.whyDecision?.risksRationale}</p>
                </div>
              </div>
            </motion.div>

            {/* Warren Buffett Value Perspective */}
            <motion.div variants={cardVariants} className="glass-card rounded-2xl p-6 md:p-8 border border-amber-500/20 relative overflow-hidden bg-gradient-to-r from-amber-500/5 to-transparent">
              <div className="absolute top-0 right-0 w-24 h-24 bg-amber-500/5 rounded-full blur-2xl pointer-events-none" />
              <h3 className="text-sm font-semibold tracking-wider text-amber-400 uppercase mb-3 flex items-center gap-2">
                <FiSmile className="text-amber-400" />
                <span>What Would Warren Buffett Think?</span>
              </h3>
              <p className="text-xs md:text-sm text-amber-200/90 leading-relaxed font-light italic whitespace-pre-line">
                "{data.buffettPerspective}"
              </p>
            </motion.div>

            {/* Detailed Analyst Rationale */}
            <motion.div variants={cardVariants} className="glass-card rounded-2xl p-6 md:p-8 border border-violet-500/15 relative overflow-hidden">
              <h3 className="text-sm font-semibold tracking-wider text-violet-400 uppercase mb-3 flex items-center gap-2">
                <FiPlusCircle />
                <span>Detailed Investment Rationale</span>
              </h3>
              <p className="text-sm md:text-base text-gray-200 leading-relaxed font-light whitespace-pre-line">
                {data.reasoning}
              </p>
            </motion.div>

          </div>
        </motion.div>
      </div>
    </div>
  );
}
